### ISSUE TITLE
Error in importing paho.mqtt.client

### ISSUE THREAD

**Issue by mudivili** [CarstenAgerskov/skill-mosquito-speak#2]
I am getting following error while running this skill.

```
File "/opt/mycroft/skills/skill-mosquito-speak/__init__.py", line 23, in <module>
import paho.mqtt.client as mqtt
ImportError: No module named paho.mqtt.client
```

I've tried installing the with pip. Nothing works! Any idea?

**Comment by CarstenAgerskov** [comment]
Thanks for reporting this problem.

Did you use the command "workon mycroft" before pip install paho-mqtt

Unfortunately I will not be able to troubleshoot on a pc until Monday.

Regards Carsten

**Comment by CarstenAgerskov** [comment]
The command sequence below installs the skill manually: 

> cd /opt/mycroft/skills/
workon mycroft 
git clone https://github.com/CarstenAgerskov/skill-mosquito-speak.git carstena-mosquito-speak
cd carstena-mosquito-speak/
workon mycroft
pip install -r requirements.txt
 
Regards Carsten

**Comment by mudivili** [comment]
@CarstenAgerskov, I tried what you said & the error disappeared. Thank you! What is the `workon` command, any way? I couldn't find any manual for that & `which` command also returns nothing!

**Comment by CarstenAgerskov** [comment]
Great that it works. I should put instructions in the readme on manual install.

workon is part of virtualenv. Virtualenv allows Python to create a virtual environment, libraries installed in a virtualenv is visible only in that environment, instead of globally. Mycroft core creates the "mycroft" environment upon installation. The Mycroft start scripts switch to the mycroft environment when running.
Documentation: http://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html#workon

Regards Carsten
